# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
defaults: 
  &something
  docker:
    - image: cimg/base:stable
  working_directory: ~/project

commands:
  print_pipeline_id:
    description: prints out the circle workflow id
    steps:
      - run:
          name: print workflow id
          command: echo $CIRCLE_WORKFLOW_ID

jobs:
  save_hello_world_output:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo $PWD > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print-my-name:
    <<: *something
    steps:
      - checkout
      - run:
          name: Print Name
          command: echo Olawale 

  print_output_file:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt
      - print_pipeline_id
      - when: on_fail

  test_error_job:
    docker:
      - image: cimg/base:stable
    steps:
      - run: exit 1
      - run:
          name: on error
          command: echo "There is an error bro!"
          when: on_fail


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  print-output-workflow:
    jobs:
      - test_error_job
      # - save_hello_world_output
      # - print_output_file:
      #     requires:
      #       - save_hello_world_output

    
